Vagrant.configure("2") do |config|
  config.vm.box = "eugenmayer/opnsense"

  config.ssh.sudo_command = "%c"
  config.ssh.shell = "/bin/sh"
  config.ssh.password = "opnsense"
  config.ssh.username = "root"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define 'opnsense' do |test|
   # Netzwerk einstellungen
    test.vm.provider 'virtualbox' do |vb|
      #NICs austauschen/switchen: LAN/WAN
      vb.customize ['modifyvm',:id, '--nic1', 'intnet', '--nic2', 'nat']
      # we forward the ports to the WebGUI/ssh since we use a nat network
      vb.customize ['modifyvm', :id, '--natpf2', "ssh,tcp,127.0.0.1,2222,,22" ] #port forward
      vb.customize ['modifyvm', :id, '--natpf2', "https,tcp,127.0.0.1,10443,,443" ] #port forward
    end
  end  
end
